### ISSUE TITLE
Include packet []byte in PacketEvent

### ISSUE THREAD

**Issue by AkihiroSuda** [osrg/earthquake#111]
Now `earthquake` has its own Ethernet inspector and does not depend on `pyearthquake` for Ethernet inspection.
So including packet `[]byte` in PacketEvent makes a sense for those who want to analyze `[]byte` in his/her own `ExplorePolicy`.
Perhaps @mitake is interested in this.

**Comment by mitake** [comment]
@AkihiroSuda yes, it would be very useful for parsing RPC messages that can be used from golang (e.g. gRPC).

**Comment by AkihiroSuda** [comment]
@mitake I closed this in #121, PTAL if you have a time.

**Comment by mitake** [comment]
@AkihiroSuda thanks, I'll look at it later.
